title: KEBA Heat Pump Dev
theme: default
views:
  - title: KEBA Heat Pump
    path: keba
    icon: mdi:heat-pump
    cards:
      - type: custom:keba-heat-pump-modbus-card
        title: KEBA Heat Pump
        view_storage_id: keba-dev-card

      - type: entities
        title: Heat Pump Status
        show_header_toggle: false
        entities:
          - entity: sensor.heat_pump_heat_pump_state
            name: State
          - entity: sensor.heat_pump_flow_temperature
            name: Flow Temperature
          - entity: sensor.heat_pump_electrical_power_consumption
            name: Power Consumption
          - entity: sensor.heat_pump_source_in_temperature
            name: Source In
          - entity: sensor.heat_pump_source_out_temperature
            name: Source Out

      - type: entities
        title: Hot Water
        show_header_toggle: false
        entities:
          - entity: sensor.hot_water_tank_top_temperature
            name: Top Temperature
          - entity: number.hot_water_tank_top_set_temperature
            name: Top Set Temperature
          - entity: select.hot_water_tank_operating_mode
            name: Operating Mode
