name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for suggesting a new feature!
- type: textarea
  id: feature-description
  attributes:
    label: Describe the feature
    description: A clear and concise description of the feature you'd like to see.
    placeholder: Tell us what you want!
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false

